
package planner;

import java.util.logging.Level;
import java.util.logging.Logger;

public class Homee extends javax.swing.JFrame {
    /**
     * Creates new form Home
     * @param name
     */
    String username;
    
    public Homee(String name) {
        initComponents();
        namaUser.setText(name);
        this.setLocationRelativeTo(null);
        username = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_Current = new javax.swing.JButton();
        BTN_History = new javax.swing.JButton();
        namaUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Current.setBackground(new java.awt.Color(255, 255, 255));
        BTN_Current.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        BTN_Current.setText("Current Weekly Planner");
        BTN_Current.setBorder(null);
        BTN_Current.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CurrentActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Current, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 595, 360, 40));

        BTN_History.setBackground(new java.awt.Color(255, 255, 255));
        BTN_History.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        BTN_History.setText("History");
        BTN_History.setBorder(null);
        BTN_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HistoryActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_History, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 240, 50));

        namaUser.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        namaUser.setForeground(new java.awt.Color(78, 118, 90));
        namaUser.setText("Sekar");
        getContentPane().add(namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 130, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/home.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CurrentActionPerformed
//         TODO add your handling code here:
        try {
            new MenuCurrent(dbconnection.Printdata(username), username, dbconnection.getList(username, "monday"), dbconnection.getList(username, "tuesday"), dbconnection.getList(username, "wednesday"), dbconnection.getList(username, "thursday"), dbconnection.getList(username, "friday"), dbconnection.getList(username, "saturday"), dbconnection.getList(username, "sunday")).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Homee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTN_CurrentActionPerformed

    private void BTN_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HistoryActionPerformed
//         TODO add your handling code here:
        try {
            new Menu_history(dbconnection.getHistoryModel(username), username).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Homee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTN_HistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homee("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Current;
    private javax.swing.JButton BTN_History;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel namaUser;
    // End of variables declaration//GEN-END:variables
}
