/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planner;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static planner.dbconnection.getCon;

    
public class Menu_history extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form Menu_history
     */
    public Menu_history(DefaultTableModel model, String user) throws SQLException, Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ResultSet rs = dbconnection.getCon().createStatement().executeQuery("SELECT * FROM history WHERE username = '" + user + "'");
        while (rs.next()) {
            String data = rs.getString("namaWeek");
            String allData[] = {data};
            DefaultTableModel mo = (DefaultTableModel)JT_History.getModel();
            mo.addRow(allData); 
        }
        username = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_See = new javax.swing.JButton();
        JB_Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_History = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_See.setBackground(new java.awt.Color(255, 255, 255));
        JB_See.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        JB_See.setText("See Row Details");
        JB_See.setBorder(null);
        JB_See.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SeeActionPerformed(evt);
            }
        });
        getContentPane().add(JB_See, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 780, 240, 40));

        JB_Back.setBackground(new java.awt.Color(255, 255, 255));
        JB_Back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        JB_Back.setText("Back");
        JB_Back.setBorder(null);
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 30));

        JT_History.setBackground(new java.awt.Color(254, 250, 229));
        JT_History.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        JT_History.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "History List"
            }
        ));
        jScrollPane1.setViewportView(JT_History);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 275, 870, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/history.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SeeActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) JT_History.getModel();
        int row = JT_History.getSelectedRow(); // row yang dipencet

        if (row == -1) {
            // No row selected, handle accordingly (show a message, return, etc.)
            JOptionPane.showMessageDialog(this, "Please select a row", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object namaweek = model.getValueAt(row, 0);
        this.dispose();
        try {
            new detail_history(username, namaweek.toString()).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Menu_history.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_SeeActionPerformed

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JB_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DefaultTableModel n = null;
                try {
                    new Menu_history(n, "").setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Menu_history.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_See;
    private javax.swing.JTable JT_History;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
