/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package planner;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class menu_insert extends javax.swing.JFrame {

    /**
     * Creates new form menu_insert
     * @param hari
     */
    String hariCurr;
    String username;
    
    public menu_insert(String hari, String user) {
        initComponents();
        CB_Category.addItem("do");
        CB_Category.addItem("decide");
        CB_Category.addItem("delegate");
        CB_Category.addItem("delete");
        hariCurr = hari;
        username = user;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Event = new javax.swing.JTextArea();
        JB_Back = new javax.swing.JButton();
        JB_Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_Category.setBackground(new java.awt.Color(254, 250, 229));
        CB_Category.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        getContentPane().add(CB_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 820, 50));

        TA_Event.setBackground(new java.awt.Color(254, 250, 229));
        TA_Event.setColumns(20);
        TA_Event.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        TA_Event.setRows(5);
        jScrollPane1.setViewportView(TA_Event);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 810, 400));

        JB_Back.setBackground(new java.awt.Color(255, 255, 255));
        JB_Back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        JB_Back.setText("Back");
        JB_Back.setBorder(null);
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 800, 80, 30));

        JB_Save.setBackground(new java.awt.Color(255, 255, 255));
        JB_Save.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        JB_Save.setText("Save");
        JB_Save.setBorder(null);
        JB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/insert.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new taskDaily(hariCurr, username, dbconnection.getListDaily(username, hariCurr, "do"), dbconnection.getListDaily(username, hariCurr, "decide"), dbconnection.getListDaily(username, hariCurr, "delegate"), dbconnection.getListDaily(username, hariCurr, "delete")).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuCurrent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_BackActionPerformed

    private void JB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveActionPerformed

        try {
            String selVal = CB_Category.getSelectedItem().toString();
            if("".equals(TA_Event.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Put your todo to the text area", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }else{
                dbconnection.InsertData("INSERT INTO weeklist (username, day, category, todo) VALUES ('" + username + "', '" + hariCurr + "', '" + selVal + "', '" + TA_Event.getText() + "')");
                JOptionPane.showMessageDialog(null, "Submitted to database");
            }
            TA_Event.setText("");
        } catch (Exception ex) {
            Logger.getLogger(menu_insert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_insert("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Category;
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_Save;
    private javax.swing.JTextArea TA_Event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
