/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planner;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static planner.dbconnection.c;
import static planner.dbconnection.getCon;

public class menu_delete extends javax.swing.JFrame {

    /**
     * Creates new form menu_delete
     * @param hari
     * @param user
     * @param listDo
     * @param listDecide
     * @param listDelegate
     * @param listDelete
     */

    String hariCurr;
    String username;
    
    public menu_delete(String hari, String user) {
        initComponents();
        hariCurr = hari;
        username = user;
        muncul();
        this.setLocationRelativeTo(null);
    }
    
    public final void muncul(){
        
        try{
            CB_Event.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/weeklyplanner", "root", "");
            ResultSet rs = c.createStatement().executeQuery("SELECT * FROM weeklist WHERE username = '" + username + "' AND day = '" + hariCurr + "'");
            while(rs.next()){
                String todo = rs.getString("todo");
                CB_Event.addItem(todo);
            }
        }catch(ClassNotFoundException | SQLException ex){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Event = new javax.swing.JComboBox<>();
        JB_Back = new javax.swing.JButton();
        JB_Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_Event.setBackground(new java.awt.Color(254, 250, 229));
        CB_Event.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        CB_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EventActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 980, 40));

        JB_Back.setBackground(new java.awt.Color(255, 255, 255));
        JB_Back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        JB_Back.setText("Back");
        JB_Back.setBorder(null);
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 80, 30));

        JB_Delete.setBackground(new java.awt.Color(255, 255, 255));
        JB_Delete.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        JB_Delete.setText("Delete");
        JB_Delete.setBorder(null);
        JB_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 705, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/delete.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EventActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CB_EventActionPerformed

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new taskDaily(hariCurr, username, dbconnection.getListDaily(username, hariCurr, "do"), dbconnection.getListDaily(username, hariCurr, "decide"), dbconnection.getListDaily(username, hariCurr, "delegate"), dbconnection.getListDaily(username, hariCurr, "delete")).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuCurrent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_BackActionPerformed

    private void JB_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DeleteActionPerformed
        try {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                dbconnection.InsertData("DELETE FROM weeklist WHERE todo = '" + CB_Event.getSelectedItem() + "' AND username = '" + username + "' AND day = '" + hariCurr + "'");
                JOptionPane.showMessageDialog(this, "Deleted !");
                muncul();
            }else{
                JOptionPane.showMessageDialog(this, "Data tidak dihapus");
            }

        } catch (Exception ex) {
            Logger.getLogger(menu_delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_delete("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Event;
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_Delete;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
