/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planner;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Lenovo
 */
public class registerPage extends javax.swing.JFrame {

    /**
     * Creates new form registerPage
     */
    public registerPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setBackground(new java.awt.Color(254, 250, 224));
        usernameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameField.setBorder(null);
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 510, 50));

        emailField.setBackground(new java.awt.Color(254, 250, 224));
        emailField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailField.setToolTipText("");
        emailField.setBorder(null);
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 510, 50));

        passwordField.setBackground(new java.awt.Color(254, 250, 224));
        passwordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordField.setBorder(null);
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 510, 50));

        registerButton.setBackground(new java.awt.Color(204, 213, 174));
        registerButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.setBorder(null);
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 685, 460, 50));

        loginButton.setBackground(new java.awt.Color(254, 250, 224));
        loginButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 17)); // NOI18N
        loginButton.setForeground(new java.awt.Color(153, 0, 0));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 780, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/sign up.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        loginPage loginFrame = new loginPage();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_loginButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        String username, email, Password, query, query2;
        String SUrl, SUser, Spassword;
        SUrl = "jdbc:MySQL://localhost:3306/planner";
        SUser = "root";
        Spassword = "";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, Spassword);
            Statement st = con.createStatement();
            if("".equals(usernameField.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Username is Required.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }else if("".equals(emailField.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Email is Required", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }else if("".equals(passwordField.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is Required", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }else{
                username = usernameField.getText();
                email = emailField.getText();
                Password = passwordField.getText();
                System.out.println(Password);

                query = "INSERT INTO pengguna(username, email, passwordUser)"+
                "VALUES('"+username+"', '"+email+"', '"+Password+"')";

                st.execute(query);
                
                query2 = "INSERT INTO notes(username) VALUES ('"  + username + "')";
                
                st.execute(query2);
                
                usernameField.setText("");
                emailField.setText("");
                passwordField.setText("");
                showMessageDialog(null, "Account has been created successfully!");
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println("Error!"+ e.getMessage());

        }
    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
