/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planner;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lenovo
 */
public class taskDaily extends javax.swing.JFrame {
    String username;
    String hariCurr;
    public taskDaily(String hari, String user, DefaultListModel listDo, DefaultListModel listDecide, DefaultListModel listDelegate, DefaultListModel listDelete) throws Exception{
        initComponents();
        L_Day.setText(hari);
        hariCurr = hari;
        username = user;
        JL_Do.setModel(listDo);
        JL_Decide.setModel(listDecide);
        JL_Delegate.setModel(listDelegate);
        JL_Delete.setModel(listDelete);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        JL_Do = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        JL_Decide = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        JL_Delegate = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        JL_Delete = new javax.swing.JList<>();
        L_Day = new javax.swing.JLabel();
        BT_Insert = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane8.setPreferredSize(new java.awt.Dimension(75, 146));

        JL_Do.setBackground(new java.awt.Color(254, 250, 229));
        JL_Do.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        jScrollPane8.setViewportView(JL_Do);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 510, 320));

        jScrollPane5.setPreferredSize(new java.awt.Dimension(75, 146));

        JL_Decide.setBackground(new java.awt.Color(254, 250, 229));
        JL_Decide.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        jScrollPane5.setViewportView(JL_Decide);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 500, 320));

        jScrollPane6.setPreferredSize(new java.awt.Dimension(75, 146));

        JL_Delegate.setBackground(new java.awt.Color(254, 250, 229));
        JL_Delegate.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        jScrollPane6.setViewportView(JL_Delegate);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 500, 510, 320));

        jScrollPane7.setPreferredSize(new java.awt.Dimension(75, 146));

        JL_Delete.setBackground(new java.awt.Color(254, 250, 229));
        JL_Delete.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        jScrollPane7.setViewportView(JL_Delete);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 500, 320));

        L_Day.setText("Hari");
        getContentPane().add(L_Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 30, -1));

        BT_Insert.setBackground(new java.awt.Color(255, 255, 255));
        BT_Insert.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        BT_Insert.setText("Insert");
        BT_Insert.setBorder(null);
        BT_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_InsertActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 840, 150, 30));

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setBorder(null);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 840, 150, 30));

        btn_delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 840, 150, 30));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(null);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 840, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/taskdaily.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_InsertActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu_insert(L_Day.getText(), username).setVisible(true);
    }//GEN-LAST:event_BT_InsertActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        this.dispose();
        new menu_edit(hariCurr, username).setVisible(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        this.dispose();
        new menu_delete(hariCurr, username).setVisible(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
        try {
            new MenuCurrent(dbconnection.Printdata(username), username, dbconnection.getList(username, "monday"), dbconnection.getList(username, "tuesday"), dbconnection.getList(username, "wednesday"), dbconnection.getList(username, "thursday"), dbconnection.getList(username, "friday"), dbconnection.getList(username, "saturday"), dbconnection.getList(username, "sunday")).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(taskDaily.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taskDaily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taskDaily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taskDaily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taskDaily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DefaultListModel n = null;
                try {
                    new taskDaily("", "", n, n, n, n).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(taskDaily.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Insert;
    private javax.swing.JList<String> JL_Decide;
    private javax.swing.JList<String> JL_Delegate;
    private javax.swing.JList<String> JL_Delete;
    private javax.swing.JList<String> JL_Do;
    private javax.swing.JLabel L_Day;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
